### PR TITLE
fix when group doesn't exist

### PR DESCRIPTION
**Pull request by inigohu**
handle FATAL ERROR when trying to openGroup but the group doesn't exist.

### CODE REVIEW

**Comment by rimmartin** [comment]
Hi, maybe we should throw an exception?

**Comment by inigohu** [comment]
Yes, it would be much better. I'm not a C++ master, but I have done my best ;-)

**Comment by NINI1988** [comment]
A exception ist better. Maybe we could add the name of the opening group to the exception like for opening a file.

And we need a test for this case.

**Comment by rimmartin** [comment]
Added unwrapping and checkig if he group id is >=0

There is an inner catch in Group::New for the actual H5Gopen call and setting th javascript throw.  The Group::Instantiate doesn't get this so cecked the id.  However there may bes a way to check for existence first I'm thinking of adding internally in the Group::New so the vebosity from H5Gopen doesn't happen

**Comment by rimmartin** [comment]
added existence check

**Pull request merged**
