### PR TITLE
Travis

### PR DESCRIPTION
**Pull request by NINI1988**
Build multiple node versions and add possibility to add multiple gcc versions.

### CODE REVIEW

**Comment by NINI1988** [comment]
Maybe we could add AppVeyor to test builds on windows?

**Comment by rimmartin** [comment]
could, does it use a different yml?

**Comment by NINI1988** [comment]
I actual don't know how it works.

**Comment by rimmartin** [comment]
we'll look into it

we are close with this matrix. On nodejs v6 on both os's get
```
Uint8Array [ 05, 04, 03, 02, 01 ] to match Uint8Array [ 05, 04, 03, 02, 01 ]
```
looks like it worked; I don't a match issue

**Comment by rimmartin** [comment]
I blocked that line "buffer.should.match(readBuffer);" with that object to object test.  This will upgrade when we take the reserved properties off

**Comment by NINI1988** [comment]
Maybe readbuffer don't have the properties rank and rows?

But blocking until the new version arrives is also OK.

**Comment by rimmartin** [comment]
might have been the type property; other ones worked where it was set for the make; but set for the make went in the past to the Buffer style; we'll reassess tests when we change this

All 8 builds green!

**Pull request merged**
