### PR TITLE
Fix unaligned access and read float32 value (it was casted as double)

### PR DESCRIPTION
**Pull request by NINI1988**
A test which tests write and read float32 values to a table should be added.

### CODE REVIEW

**Comment by NINI1988** [comment]
Yes, that's right for Javascript. But the data array comes from c hdf lib. 

What's different in Darwin boxes?

**Comment by rimmartin** [comment]
The order of bytes.  So far noone has run into making datasets on one OS and reading on another.  From what I've read the javascript is not system agnostic

**Comment by NINI1988** [comment]
I dont write and read on another OS. But HDF5 is portable.

The problem was that the byte array from the hdf5 C lib which contains float data, was casted to a double array.

<table>
  <tr>
    <th>byte</th>
    <th>0</th>
    <th>1</th>
    <th>2</th>
    <th>3<br></th>
    <th>4</th>
    <th>5</th>
    <th>6</th>
    <th>7</th>
  </tr>
  <tr>
    <td>float</td>
    <td colspan="4">0</td>
    <td colspan="4">1</td>
  </tr>
  <tr>
    <td>double</td>
    <td colspan="8">0</td>
  </tr>
</table>

So the result of double casting is the concatenation of two float values.

**Comment by rimmartin** [comment]
I supposed depends on compiler; before it was doing a promotional conversion http://www.cplusplus.com/doc/tutorial/typecasting/ without compiler warnings


Now a static_cast<double>(value) I believe would do what you describe

**Comment by NINI1988** [comment]
I don't know. But reading float32 values returns only zero vales before the change.

**Comment by rimmartin** [comment]
Interesting; I'd need to know more about your compiler and settings.

Can you see the unit tests runs on travis-ci( or can only I see?

The unit tests check for numbers matching

**Comment by rimmartin** [comment]
Albeit the tests are passing and it is cool getting this working on an arm

**Comment by NINI1988** [comment]
The float32 reading fails on Win64. I can also see the Travis results. I'll get a little bit into it tomorrow, when I have some time.

**Comment by NINI1988** [comment]
On the first look, there ist no float32array test.

**Pull request merged**
