### PR TITLE
Fix issues

### PR DESCRIPTION
**Pull request by romgrk**
Hey,

This PR solves a few issues:

1. It's currently impossible to specify dimensions for string type datasets. It is made possible with this PR.
2. Whenever there is an HDF5 library error, `SyntaxError`s are being thrown. SyntaxError in javascript is specifically for javascript parsing errors, when in doubt `Error` should be used.
3. Fixed a few deprecations for newer versions of nodejs. Still doesnt compile with the latest version but there will be less work to do with these changes.

What do you think would be the timeline for merging and deploying this PR? I'm working on a loompy module for node that depends on this, for an implementation of [ga4gh-rnaseq](https://github.com/ga4gh-rnaseq/schema), and we hope to deploy it as soon as possible, so any diligence in approving this would be greatly appreciated.

Thanks,

Romain

### CODE REVIEW

**Comment by romgrk** [comment]
There are a few more issues that I'd like to fix with this PR:
 - Make it possible to create datasets of fixed-size string
 - Make it possible to specify the string-padding for string datatypes
 - Make it possible to specify the string-padding for string attributes

**Comment by romgrk** [comment]
I've finished working on those issues.

A new method was implemented on `File` and `Group`, `.setAttribute(name: string, value: any, options?: { padding: boolean })`.

**Comment by romgrk** [comment]
One more change:

`file.close()` now throws when there are still open groups, as it would cause (weird) bugs further down the road not to.

**Comment by rimmartin** [comment]
Hi @romgrk , been away for a bit; let me look at why the travis failure and get this merged

**Comment by rimmartin** [comment]
Note;the code for node version v12 has been done in branch https://github.com/HDF-NI/hdf5.node/tree/v12

**Comment by rimmartin** [comment]
I'll write the essence of what you want in the two branches master and v12.

Still deciding if everybody is ready to go to v12 and make all prior versions pull from this repository and publish the v12 version to npm

**Comment by rimmartin** [comment]
on the file.close() how are you using the v8::Exception::Error's on the js side?  Hopefully not having to parse the error message.

My intention was to add a debug config that showed these; and users debug to make sure things are closing at the proper place & time.

Or would a list of h5 types and id's set for the v8::Exception::Error be useful?

**Comment by romgrk** [comment]
in `file.close()`, I've made it an error to leave groups unclosed before closing a file. Otherwise the resulting file can be invalid.

You're free to cherry-pick the commits you wish to include in other branches. I'm using a local fork of this package for my use-case, I needed the ability to set the string-padding & other things when creating datatypes.

**Comment by rimmartin** [comment]
Hi @romgrk, I made file.close() an accumulated exception error when groups and other objects aren't closed.   The current exception error msg can be a bit messy and if you want to do more with it than just read it maybe a list could also be returned.   

Will be looking again at a debug configuration with gyp to help users get objects closed

I'll be adding the fixed and padded strings; looking also at all the datatypes, attributes and dimensions in https://github.com/HDF-NI/hdf5.node/issues/105 to complete many more possibilities for users

The SyntaxError has been replaced with Error; will look thru the v8 categories to see what specific per error can be used

**Comment by romgrk** [comment]
Ok! Well if it's all handled in other places you can close this.

**Comment by rimmartin** [comment]
Eventually, this is good set of things to work in.  Thank you @romgrk

**Comment by rimmartin** [comment]
HI @romgrk ,

when it comes to multi rank fixed string datasets what do you like for the javascript side?  My trend is to get away from nodejs Buffer which is a single Uint8Array and  implemented a Array of Array's interface.

I've been working on a pure JavaScript implementation that is compatible with nodejs but can be used with any javascript engine.  The Javascript side of hdf5.node will remain the same with additions and for a time I'll provide a nodejs Buffer but it will become deprecated.

Ill add to the gh pages more reference and tutorials

**Comment by chadbr** [comment]
I assume this for strings, not numbers?

**Comment by romgrk** [comment]
It sounds good to me for most cases. JS Strings have the inconvenience that `.length` returns the character length and not the byte length, but Buffer is less idiomatic.

**Comment by rimmartin** [comment]
@chadbr yes strings; numbers go to the JS typed arrays if possible or if you choose the Buffer; I'm not a big fan of the Buffer since it is Uint8Array which limits size by JS's largest int divided by bytes per entry

@romgrk  with the array of arrays the limiting size is on the column; not the whole dataset size.  You're right the JS representation/dimensioning is a factor.  I'm working to enable getting a subset of multi rank string datasets with the options {start: [1,2], stride: [1,1], count: [3,4]} as other datasets.  In case someone needs to go after an h5 with data larger than the upper limit of JS int(unless they've added it there is not even 64 bit but 53 bit)

**Pull request closed without merging**
