### PR TITLE
Latest Node API + various cleanup

### PR DESCRIPTION
**Pull request by Y--**

### CODE REVIEW

**Comment by Y--** [comment]
Thanks a lot for the merge @rimmartin !

**Comment by rimmartin** [comment]
Thanks for the yeomen work:-)

I'll look thru and update the documentation

**Comment by rimmartin** [comment]
And test my stuff and then publish to npm

**Comment by Y--** [comment]
Awesome, thanks a lot!

Would you be interested in a PR that would normalize the code and remove the commented out pieces?
We would use clang-format for that : https://clang.llvm.org/docs/ClangFormat.html

**Comment by rimmartin** [comment]
absolutely!  Now would be a great time.

So that I stay compatible what clang formatter do you use?  I've used netbeans in the past for formatting but I don't recall a clang format choice there

**Comment by Y--** [comment]
Excellent, I've submitted this PR https://github.com/HDF-NI/hdf5.node/pull/39
The .clang-format configuration file is also included in the source file.
Of course this is just a suggestion, we can definitely adjust it and I will update the PR.

Thanks a lot!

**Pull request merged**
